apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: database-persistent-volume-claim 
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 2Gi  # k8s must find a storage option that has exactly 2 Gigabytes
