apiVersion: apps/v1
metadata: 
  name: postgres-deployment
spec: 
  replicas: 1 
  selector:   
    matchLabels: 
      component: postgres 
  template: 
    metadata: 
      labels: 
        component: postgres 
    spec: 
      container: 
        - name: postgres 
          image: postgres 
          ports: 
            - containerPort: 5432