apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
# specifications for deployment 
spec: 
  replicas: 3 
  selector: 
    matchLabels: # is a map of key/value pairs  "matchLabels": {"component": "server"}
      component: server 
  template: # Template defines the pods that will be created from this pod template. 
    metadata: 
      labels: 
        component: server 
    # specifications for container
    spec: 
      containers: 
        - name: server 
          image: sergiopichardo/multi-server 
          ports: 
            - containerPort: 5000 
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: 6379
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: 5432
              # this is stored as a kubernetes secret
            - name: POSTGRES_PASSWORD   # name of env variable
              valueFrom: 
                secretKeyRef: 
                  name: postgrespassword
                  key: POSTGRES_PASSWORD    # secret's key
